# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 21:24
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(default=time.time, max_length=10, verbose_name='新闻 id')),
                ('news_name', models.CharField(max_length=30, verbose_name='新闻标题')),
                ('news_text', ckeditor.fields.RichTextField(verbose_name='新闻内容')),
                ('news_img', models.ImageField(default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='新闻封面')),
                ('news_add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
