# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(verbose_name='新闻id'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(default='image/default.png', null=True, upload_to='image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(null=True, verbose_name='新闻内容（文字）'),
        ),
    ]
