# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moments_id', models.IntegerField(verbose_name='说说id')),
                ('moments_user', models.CharField(max_length=50, verbose_name='用户')),
                ('moments_text', models.TextField(verbose_name='说说正文')),
                ('moments_img', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('moments_like', models.IntegerField(verbose_name='点赞数')),
                ('moments_comment', models.TextField(verbose_name='评论')),
                ('moments_add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '用户说说信息',
            },
        ),
    ]
