# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moments_id', models.IntegerField(verbose_name='说说id')),
                ('moments_text', models.TextField(verbose_name='说说正文')),
                ('moments_img', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='图片信息')),
                ('moments_like', models.IntegerField(verbose_name='点赞数')),
                ('moments_comment', models.TextField(verbose_name='评论')),
                ('has_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('moments_add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='说说添加时间')),
                ('user_friends_id', models.TextField(null=True, verbose_name='用户好友ID')),
            ],
            options={
                'verbose_name': '用户说说信息',
                'verbose_name_plural': '用户说说信息',
            },
        ),
    ]
