# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_moments_moments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moments',
            options={'verbose_name': '用户说说信息', 'verbose_name_plural': '用户说说信息'},
        ),
        migrations.AddField(
            model_name='moments',
            name='has_delete',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='moments',
            name='moments_add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='说说添加时间'),
        ),
        migrations.AlterField(
            model_name='moments',
            name='moments_img',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='图片信息'),
        ),
    ]
