# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-14 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0002_auto_20180413_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friends_list', models.IntegerField(verbose_name='好友列表')),
                ('moments_add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.UserMessage', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户列表',
            },
        ),
    ]
