# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friends_list', models.IntegerField(verbose_name='好友列表')),
                ('moments_add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '好友列表',
                'verbose_name_plural': '好友列表',
            },
        ),
    ]
