# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 09:05
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='user_department',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('Node.js', 'Node.js'), ('Python', 'Python'), ('Frontend', '前端'), ('others', '其他')], default='', max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_desc',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='个人描述'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_sinature',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
