# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='user_department',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('Node.js', 'Node.js'), ('Python', 'Python'), ('Frontend', '前端'), ('others', '其他')], default='', max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_desc',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='个人描述'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_signature',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
