# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user_collect',
        ),
    ]
