# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
