# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20180506_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='user_sinature',
            new_name='user_signature',
        ),
    ]
