# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20180412_1719'),
        ('user_info', '0002_remove_usermessage_user_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='user_collect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collect.Collect', verbose_name='用户收藏'),
            preserve_default=False,
        ),
    ]
